// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Core.Data;

#nullable disable

namespace api.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 1
                        },
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 2
                        },
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 3
                        },
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 4
                        },
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 5
                        },
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 6
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 7
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 8
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 9
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 10
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 11
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 12
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 13
                        },
                        new
                        {
                            RolesId = 2,
                            PermissionsId = 14
                        },
                        new
                        {
                            RolesId = 1,
                            PermissionsId = 15
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UsersId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            UsersId = 1,
                            RolesId = 2
                        });
                });

            modelBuilder.Entity("api.Modules.Notifications.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalizationArgs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocalizationKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("api.Modules.Notifications.Models.UserNotification", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("api.Modules.Permissions.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = 0,
                            Code = "users.read",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        },
                        new
                        {
                            Id = 2,
                            Action = 1,
                            Code = "users.write",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        },
                        new
                        {
                            Id = 3,
                            Action = 2,
                            Code = "users.delete",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        },
                        new
                        {
                            Id = 4,
                            Action = 0,
                            Code = "roles.read",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        },
                        new
                        {
                            Id = 5,
                            Action = 1,
                            Code = "roles.write",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        },
                        new
                        {
                            Id = 6,
                            Action = 2,
                            Code = "roles.delete",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        },
                        new
                        {
                            Id = 7,
                            Action = 0,
                            Code = "profile.read",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 8,
                            Action = 1,
                            Code = "profile.write",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 9,
                            Action = 0,
                            Code = "files.read",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 10,
                            Action = 1,
                            Code = "files.write",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 11,
                            Action = 2,
                            Code = "files.delete",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 12,
                            Action = 0,
                            Code = "notifications.read",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 13,
                            Action = 1,
                            Code = "notifications.write",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 14,
                            Action = 2,
                            Code = "notifications.delete",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 1
                        },
                        new
                        {
                            Id = 15,
                            Action = 0,
                            Code = "traces.read",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = true,
                            Group = 0
                        });
                });

            modelBuilder.Entity("api.Modules.Permissions.Models.PermissionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId", "Locale")
                        .IsUnique();

                    b.ToTable("PermissionTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Denomination = "Read users",
                            Description = "Read all users",
                            Locale = "en-US",
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Denomination = "Write users",
                            Description = "Create or Update users",
                            Locale = "en-US",
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Denomination = "Delete users",
                            Description = "Delete users",
                            Locale = "en-US",
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Denomination = "Read roles",
                            Description = "Read roles",
                            Locale = "en-US",
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Denomination = "Write roles",
                            Description = "Create or Update roles",
                            Locale = "en-US",
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Denomination = "Delete roles",
                            Description = "Delete roles",
                            Locale = "en-US",
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 7,
                            Denomination = "Read profile",
                            Description = "Read user profile",
                            Locale = "en-US",
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 8,
                            Denomination = "Write profile",
                            Description = "Update user profile",
                            Locale = "en-US",
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 9,
                            Denomination = "Read files",
                            Description = "Read files",
                            Locale = "en-US",
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 10,
                            Denomination = "Write files",
                            Description = "Upload files",
                            Locale = "en-US",
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 11,
                            Denomination = "Delete files",
                            Description = "Delete files",
                            Locale = "en-US",
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 12,
                            Denomination = "Read notifications",
                            Description = "Read system notifications",
                            Locale = "en-US",
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 13,
                            Denomination = "Mark notifications as read",
                            Description = "Mark all system notifications as read",
                            Locale = "en-US",
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 14,
                            Denomination = "Delete notifications",
                            Description = "Delete system notifications",
                            Locale = "en-US",
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 15,
                            Denomination = "Read traces",
                            Description = "Read system traces",
                            Locale = "en-US",
                            PermissionId = 15
                        },
                        new
                        {
                            Id = 16,
                            Denomination = "Leer usuarios",
                            Description = "Leer todos los usuarios",
                            Locale = "es-ES",
                            PermissionId = 1
                        },
                        new
                        {
                            Id = 17,
                            Denomination = "Escribir usuarios",
                            Description = "Crear o actualizar usuarios",
                            Locale = "es-ES",
                            PermissionId = 2
                        },
                        new
                        {
                            Id = 18,
                            Denomination = "Eliminar usuarios",
                            Description = "Eliminar usuarios",
                            Locale = "es-ES",
                            PermissionId = 3
                        },
                        new
                        {
                            Id = 19,
                            Denomination = "Leer roles",
                            Description = "Leer roles",
                            Locale = "es-ES",
                            PermissionId = 4
                        },
                        new
                        {
                            Id = 20,
                            Denomination = "Escribir roles",
                            Description = "Crear o actualizar roles",
                            Locale = "es-ES",
                            PermissionId = 5
                        },
                        new
                        {
                            Id = 21,
                            Denomination = "Eliminar roles",
                            Description = "Eliminar roles",
                            Locale = "es-ES",
                            PermissionId = 6
                        },
                        new
                        {
                            Id = 22,
                            Denomination = "Leer perfil",
                            Description = "Leer perfil de usuario",
                            Locale = "es-ES",
                            PermissionId = 7
                        },
                        new
                        {
                            Id = 23,
                            Denomination = "Escribir perfil",
                            Description = "Actualizar perfil de usuario",
                            Locale = "es-ES",
                            PermissionId = 8
                        },
                        new
                        {
                            Id = 24,
                            Denomination = "Leer ficheros",
                            Description = "Leer ficheros",
                            Locale = "es-ES",
                            PermissionId = 9
                        },
                        new
                        {
                            Id = 25,
                            Denomination = "Subir ficheros",
                            Description = "Subir ficheros",
                            Locale = "es-ES",
                            PermissionId = 10
                        },
                        new
                        {
                            Id = 26,
                            Denomination = "Eliminar ficheros",
                            Description = "Eliminar ficheros",
                            Locale = "es-ES",
                            PermissionId = 11
                        },
                        new
                        {
                            Id = 27,
                            Denomination = "Leer notificaciones",
                            Description = "Leer notificaciones del sistema",
                            Locale = "es-ES",
                            PermissionId = 12
                        },
                        new
                        {
                            Id = 28,
                            Denomination = "Marcar notificaciones como leídas",
                            Description = "Marcar las notificaciones del sistema como leídas",
                            Locale = "es-ES",
                            PermissionId = 13
                        },
                        new
                        {
                            Id = 29,
                            Denomination = "Eliminar notificaciones",
                            Description = "Eliminar notificaciones del sistema",
                            Locale = "es-ES",
                            PermissionId = 14
                        },
                        new
                        {
                            Id = 30,
                            Denomination = "Leer trazas",
                            Description = "Leer las trazas del sistema",
                            Locale = "es-ES",
                            PermissionId = 15
                        });
                });

            modelBuilder.Entity("api.Modules.Roles.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Denomination")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = false,
                            Denomination = "Super Admin",
                            Description = "Super administrator",
                            Enabled = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = false,
                            Denomination = "User",
                            Description = "Basic user",
                            Enabled = true
                        });
                });

            modelBuilder.Entity("api.Modules.Traces.Models.Trace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocalizationArgs")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LocalizationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trace");
                });

            modelBuilder.Entity("api.Modules.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "",
                            CreatedAt = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deletable = false,
                            Email = "superAdmin@domain.com",
                            FullName = "Super Administrator",
                            Password = "$2a$12$is8ljKUP99p7UlgoBQgCSOZDVQfeKwqSmYgkLpASj3DBbzxTxqSyq",
                            Phone = "+5312345678",
                            Status = 0,
                            Username = "superAdmin"
                        });
                });

            modelBuilder.Entity("api.Modules.VerificationCodes.Models.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deletable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Code", "Type");

                    b.ToTable("VerificationCode");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("api.Modules.Permissions.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Modules.Roles.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("api.Modules.Roles.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Modules.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Modules.Notifications.Models.UserNotification", b =>
                {
                    b.HasOne("api.Modules.Notifications.Models.Notification", "Notification")
                        .WithMany("Users")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Modules.Users.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.Permissions.Models.PermissionTranslation", b =>
                {
                    b.HasOne("api.Modules.Permissions.Models.Permission", "Permission")
                        .WithMany("Translations")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("api.Modules.Traces.Models.Trace", b =>
                {
                    b.HasOne("api.Modules.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.VerificationCodes.Models.VerificationCode", b =>
                {
                    b.HasOne("api.Modules.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.Notifications.Models.Notification", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("api.Modules.Permissions.Models.Permission", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("api.Modules.Users.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
