//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("api.Modules.Localization.Resources.SharedResource_en_US", typeof(SharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        internal static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string RoleFound {
            get {
                return ResourceManager.GetString("RoleFound", resourceCulture);
            }
        }
        
        internal static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        internal static string PermissionsNotFound {
            get {
                return ResourceManager.GetString("PermissionsNotFound", resourceCulture);
            }
        }
        
        internal static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        internal static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        internal static string PhoneInUse {
            get {
                return ResourceManager.GetString("PhoneInUse", resourceCulture);
            }
        }
        
        internal static string DenominationInUse {
            get {
                return ResourceManager.GetString("DenominationInUse", resourceCulture);
            }
        }
        
        internal static string CreateUserError {
            get {
                return ResourceManager.GetString("CreateUserError", resourceCulture);
            }
        }
        
        internal static string UpdateUserError {
            get {
                return ResourceManager.GetString("UpdateUserError", resourceCulture);
            }
        }
        
        internal static string CreateRoleError {
            get {
                return ResourceManager.GetString("CreateRoleError", resourceCulture);
            }
        }
        
        internal static string UpdateRoleError {
            get {
                return ResourceManager.GetString("UpdateRoleError", resourceCulture);
            }
        }
        
        internal static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        internal static string VerificationEmailFailed {
            get {
                return ResourceManager.GetString("VerificationEmailFailed", resourceCulture);
            }
        }
        
        internal static string PasswordResetEmailFailed {
            get {
                return ResourceManager.GetString("PasswordResetEmailFailed", resourceCulture);
            }
        }
        
        internal static string CreateVerificationCodeFailed {
            get {
                return ResourceManager.GetString("CreateVerificationCodeFailed", resourceCulture);
            }
        }
        
        internal static string UpdateVerificationCodeFailed {
            get {
                return ResourceManager.GetString("UpdateVerificationCodeFailed", resourceCulture);
            }
        }
        
        internal static string EmailVerificationPending {
            get {
                return ResourceManager.GetString("EmailVerificationPending", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        internal static string RequestCancelled {
            get {
                return ResourceManager.GetString("RequestCancelled", resourceCulture);
            }
        }
        
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        internal static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        internal static string NotificationsNotFound {
            get {
                return ResourceManager.GetString("NotificationsNotFound", resourceCulture);
            }
        }
        
        internal static string CreateUserTrace {
            get {
                return ResourceManager.GetString("CreateUserTrace", resourceCulture);
            }
        }
        
        internal static string UpdateUserTrace {
            get {
                return ResourceManager.GetString("UpdateUserTrace", resourceCulture);
            }
        }
        
        internal static string DeleteUserTrace {
            get {
                return ResourceManager.GetString("DeleteUserTrace", resourceCulture);
            }
        }
        
        internal static string CreateRoleTrace {
            get {
                return ResourceManager.GetString("CreateRoleTrace", resourceCulture);
            }
        }
        
        internal static string UpdateRoleTrace {
            get {
                return ResourceManager.GetString("UpdateRoleTrace", resourceCulture);
            }
        }
        
        internal static string DeleteRoleTrace {
            get {
                return ResourceManager.GetString("DeleteRoleTrace", resourceCulture);
            }
        }
    }
}
