//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("api.Modules.Localization.Resources.SharedResource.es-ES", typeof(SharedResource_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta de usuario está inactiva.
        /// </summary>
        internal static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cuenta de usuario está bloqueada.
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La autenticación ha fallado.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear el usuario.
        /// </summary>
        internal static string CreateRoleError {
            get {
                return ResourceManager.GetString("CreateRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: &apos;{0}&apos; ha creado un nuevo rol con denominación: &apos;{1}&apos;.
        /// </summary>
        internal static string CreateRoleTrace {
            get {
                return ResourceManager.GetString("CreateRoleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear el usuario.
        /// </summary>
        internal static string CreateUserError {
            get {
                return ResourceManager.GetString("CreateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: &apos;{0}&apos; ha creado un nuevo usuario con nombre de usuario: &apos;{1}&apos; y correo electrónico: &apos;{2}&apos;.
        /// </summary>
        internal static string CreateUserTrace {
            get {
                return ResourceManager.GetString("CreateUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear el código de verificación.
        /// </summary>
        internal static string CreateVerificationCodeFailed {
            get {
                return ResourceManager.GetString("CreateVerificationCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: &apos;{0}&apos; ha eliminado el rol con denominación: &apos;{1}&apos;.
        /// </summary>
        internal static string DeleteRoleTrace {
            get {
                return ResourceManager.GetString("DeleteRoleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: &apos;{0}&apos; ha eliminado al usuario con nombre de usuario: &apos;{1}&apos; y correo electrónico: &apos;{2}&apos;.
        /// </summary>
        internal static string DeleteUserTrace {
            get {
                return ResourceManager.GetString("DeleteUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La denominación &apos;{0}&apos; ya está en uso.
        /// </summary>
        internal static string DenominationInUse {
            get {
                return ResourceManager.GetString("DenominationInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su correo electrónico ya ha sido verificado.
        /// </summary>
        internal static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico &apos;{0}&apos; ya está en uso.
        /// </summary>
        internal static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico pendiente de verificación. Se ha enviado un nuevo correo de verificación.
        /// </summary>
        internal static string EmailVerificationPending {
            get {
                return ResourceManager.GetString("EmailVerificationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad no encontrada.
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El fichero está vacío.
        /// </summary>
        internal static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichero no encontrado.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo al guardar el fichero.
        /// </summary>
        internal static string FileSaveFailed {
            get {
                return ResourceManager.GetString("FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los ficheros están vacíos.
        /// </summary>
        internal static string FilesEmpty {
            get {
                return ResourceManager.GetString("FilesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño del fichero excede el límite permitido.
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficheros no encontrados.
        /// </summary>
        internal static string FilesNotFound {
            get {
                return ResourceManager.GetString("FilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error interno.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales inválidas.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fichero incorrecto. Solamente se permiten JPEG, PNG and GIF.
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña no válida.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación no válido.
        /// </summary>
        internal static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación no encontrada.
        /// </summary>
        internal static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones no encontradas.
        /// </summary>
        internal static string NotificationsNotFound {
            get {
                return ResourceManager.GetString("NotificationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al enviar el correo de reinicio de contraseña.
        /// </summary>
        internal static string PasswordResetEmailFailed {
            get {
                return ResourceManager.GetString("PasswordResetEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los permisos seleccionados no existen.
        /// </summary>
        internal static string PermissionsNotFound {
            get {
                return ResourceManager.GetString("PermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de teléfono &apos;{0}&apos; ya está en uso.
        /// </summary>
        internal static string PhoneInUse {
            get {
                return ResourceManager.GetString("PhoneInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud cancelada.
        /// </summary>
        internal static string RequestCancelled {
            get {
                return ResourceManager.GetString("RequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de solicitud agotado.
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol no encontrado.
        /// </summary>
        internal static string RoleFound {
            get {
                return ResourceManager.GetString("RoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los roles seleccionados no existen.
        /// </summary>
        internal static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo al crear o accerder al directorio de almacenamiento.
        /// </summary>
        internal static string StorageDirectoryError {
            get {
                return ResourceManager.GetString("StorageDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demasiadas solicitudes realizadas, por favor intente más tarde.
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está autorizado a acceder al servicio solicitado.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al actualizar el usuario.
        /// </summary>
        internal static string UpdateRoleError {
            get {
                return ResourceManager.GetString("UpdateRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: &apos;{0}&apos; ha actualizado el rol con denominación: &apos;{1}&apos;.
        /// </summary>
        internal static string UpdateRoleTrace {
            get {
                return ResourceManager.GetString("UpdateRoleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al actualizar el usuario.
        /// </summary>
        internal static string UpdateUserError {
            get {
                return ResourceManager.GetString("UpdateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario: &apos;{0}&apos; ha actualizado al usuario con nombre de usuario: &apos;{1}&apos; y correo electrónico: &apos;{2}&apos;.
        /// </summary>
        internal static string UpdateUserTrace {
            get {
                return ResourceManager.GetString("UpdateUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al actualizar el código de verificación.
        /// </summary>
        internal static string UpdateVerificationCodeFailed {
            get {
                return ResourceManager.GetString("UpdateVerificationCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario &apos;{0}&apos; ya está en uso.
        /// </summary>
        internal static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} se ha registrado con el correo electrónico {1}.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al enviar el correo de verificación.
        /// </summary>
        internal static string VerificationEmailFailed {
            get {
                return ResourceManager.GetString("VerificationEmailFailed", resourceCulture);
            }
        }
    }
}
