//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("api.Modules.Localization.Resources.SharedResource.en-US", typeof(SharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is not active.
        /// </summary>
        internal static string AccountInactive {
            get {
                return ResourceManager.GetString("AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is locked.
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the role.
        /// </summary>
        internal static string CreateRoleError {
            get {
                return ResourceManager.GetString("CreateRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &apos;{0}&apos; has created a new role with denomination: &apos;{1}&apos;.
        /// </summary>
        internal static string CreateRoleTrace {
            get {
                return ResourceManager.GetString("CreateRoleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the user.
        /// </summary>
        internal static string CreateUserError {
            get {
                return ResourceManager.GetString("CreateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &apos;{0}&apos; has created a new user with username: &apos;{1}&apos; and email: &apos;{2}&apos;.
        /// </summary>
        internal static string CreateUserTrace {
            get {
                return ResourceManager.GetString("CreateUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the verification code.
        /// </summary>
        internal static string CreateVerificationCodeFailed {
            get {
                return ResourceManager.GetString("CreateVerificationCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &apos;{0}&apos; has deleted the role with denomination: &apos;{1}&apos;.
        /// </summary>
        internal static string DeleteRoleTrace {
            get {
                return ResourceManager.GetString("DeleteRoleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &apos;{0}&apos; has deleted the user with username: &apos;{1}&apos; and email: &apos;{2}&apos;.
        /// </summary>
        internal static string DeleteUserTrace {
            get {
                return ResourceManager.GetString("DeleteUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The denomination &apos;{0}&apos; is already in use.
        /// </summary>
        internal static string DenominationInUse {
            get {
                return ResourceManager.GetString("DenominationInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is already verified.
        /// </summary>
        internal static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already in use.
        /// </summary>
        internal static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification pending. A new verification email was sent.
        /// </summary>
        internal static string EmailVerificationPending {
            get {
                return ResourceManager.GetString("EmailVerificationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty.
        /// </summary>
        internal static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file.
        /// </summary>
        internal static string FileSaveFailed {
            get {
                return ResourceManager.GetString("FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files are empty.
        /// </summary>
        internal static string FilesEmpty {
            get {
                return ResourceManager.GetString("FilesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the allowed limit.
        /// </summary>
        internal static string FileSizeExceeded {
            get {
                return ResourceManager.GetString("FileSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files not found.
        /// </summary>
        internal static string FilesNotFound {
            get {
                return ResourceManager.GetString("FilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Only JPEG, PNG and GIF are allowed.
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code.
        /// </summary>
        internal static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification not found.
        /// </summary>
        internal static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications not found.
        /// </summary>
        internal static string NotificationsNotFound {
            get {
                return ResourceManager.GetString("NotificationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while sending the reset password email.
        /// </summary>
        internal static string PasswordResetEmailFailed {
            get {
                return ResourceManager.GetString("PasswordResetEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected permissions do not exist.
        /// </summary>
        internal static string PermissionsNotFound {
            get {
                return ResourceManager.GetString("PermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is already in use.
        /// </summary>
        internal static string PhoneInUse {
            get {
                return ResourceManager.GetString("PhoneInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cancelled.
        /// </summary>
        internal static string RequestCancelled {
            get {
                return ResourceManager.GetString("RequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out.
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        internal static string RoleFound {
            get {
                return ResourceManager.GetString("RoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected roles do not exist.
        /// </summary>
        internal static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create or access storage directory.
        /// </summary>
        internal static string StorageDirectoryError {
            get {
                return ResourceManager.GetString("StorageDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests, please try later.
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are unauthorized for the requested service.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the role.
        /// </summary>
        internal static string UpdateRoleError {
            get {
                return ResourceManager.GetString("UpdateRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &apos;{0}&apos; has updated the role with denomination: &apos;{1}&apos;.
        /// </summary>
        internal static string UpdateRoleTrace {
            get {
                return ResourceManager.GetString("UpdateRoleTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the user.
        /// </summary>
        internal static string UpdateUserError {
            get {
                return ResourceManager.GetString("UpdateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &apos;{0}&apos; has updated the user with username: &apos;{1}&apos; and email: &apos;{2}&apos;.
        /// </summary>
        internal static string UpdateUserTrace {
            get {
                return ResourceManager.GetString("UpdateUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the verification code.
        /// </summary>
        internal static string UpdateVerificationCodeFailed {
            get {
                return ResourceManager.GetString("UpdateVerificationCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already in use.
        /// </summary>
        internal static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} has been registered with the email {1}.
        /// </summary>
        internal static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while sending the verification email.
        /// </summary>
        internal static string VerificationEmailFailed {
            get {
                return ResourceManager.GetString("VerificationEmailFailed", resourceCulture);
            }
        }
    }
}
